method: grid
metric:
  goal: maximize
  name: CV Average Validation set accuracy
parameters:
  Aggregated_Comparison:
    values:
      - 0
  dataset:
    values:
      - adult
  batch_size:
    values:
      - 512
  lambda_s:
    values:
      - 0.1
      - 1
      - 10
      - 100
      - 1000
  class_weights:
    values:
      - not_applied
  dropout:
    values:
      - 0
  encoding:
    values:
      - one_hot
  epochs:
    values:
      - 120
  layer_size:
    values:
      - 1
      - 3
      - 5
  learning_rate:
    values:
      - 0.001
  num_hidden_layers:
    values:
      - 1
      - 3
      - 5
  optimizer_name:
    values:
      - adam
  weight_decay:
    values:
      - 0
  reconstruction_method:
    values:
      - minmax
program: source/attacks/CVE_attack.py
