method: grid
metric:
  goal: maximize
  name: LSB Test set accuracy
parameters:
  dataset:
    values:
      - adult
  type:
    values:
      - benign
  encoding_into_bits:
    values:
      - direct
      - gzip
      - RDCodec
  exfiltration_encoding:
    values:
      - label
      - one_hot
  num_hidden_layers:
    values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 10
  layer_size:
    values:
      - 1
      - 2
      - 3
      - 4
      - 5
  dropout:
      values:
      - 0.0
  learning_rate:
    values:
      - 0.001
  batch_size:
    values:
      - 512
  n_lsbs:
    values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
  n_defense_lsbs:
    values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
program: LSB_attack.py