method: grid
metric:
  goal: maximize
  name: LSB Test set accuracy
parameters:
  dataset:
    values:
      - adult
  type:
    values:
      - benign
  encoding_into_bits:
    values:
      - direct
  exfiltration_encoding:
    values:
      - one_hot
  num_hidden_layers:
    values:
      - 1
  layer_size:
    values:
      - 1
  dropout:
      values:
      - 0.0
  learning_rate:
    values:
      - 0.001
  batch_size:
    values:
      - 512
  n_lsbs:
    values:
      - 20
  n_defense_lsbs:
    values:
      - 5
  optimizer:
    values:
      - adam
program: LSB_attack.py