method: grid
metric:
  goal: maximize
  name: LSB Test set accuracy
parameters:
  dataset:
    values:
      - adult
  type:
    values:
      - benign
  encoding_into_bits:
    values:
      - gzip
  n_ecc:
    values:
      - 5
  exfiltration_encoding:
    values:
      - label
  num_hidden_layers:
    values:
      - 2
  layer_size:
    values:
      - 2
  dropout:
      values:
      - 0.0
  learning_rate:
    values:
      - 0.001
  batch_size:
    values:
      - 512
  n_lsbs:
    values:
      - 3
  n_defense_lsbs:
    values:
      - 5
  optimizer:
    values:
      - adam

program: LSB_attack.py