wandb_version: 1

Aggregated_Comparison:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    code_path: code/train_adult.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1678376713.897325
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 2
      - 3
      - 23
      - 37
      4: 3.6.13
      5: 0.13.10
      8:
      - 5
    visualize:
      Test set CM:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Test set CM_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      Train set CM:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Train set CM_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      Validation set CM:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Validation set CM_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
batch_size:
  desc: null
  value: 256
class_weights:
  desc: null
  value: not_applied
dropout:
  desc: null
  value: 0
encoding:
  desc: null
  value: one_hot
epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.001
m1:
  desc: null
  value: 16
m2:
  desc: null
  value: 16
m3:
  desc: null
  value: 1
m4:
  desc: null
  value: 16
optimizer:
  desc: null
  value: adam
threshold:
  desc: null
  value: 0.5
weight_decay:
  desc: null
  value: 0
